<?php $this->extend('Modules\User\Views\home') ?>


<?php $this->section('title') ?>

Terms & Conditions

<?php $this->endsection() ?>


<?php $this->section('styles') ?>
<!-- Styles will go here -->

<?php $this->endsection() ?>



<?php $this->section('content') ?>

<main id="main">

    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">
        <div class="container">

            <div class="d-flex justify-content-between align-items-center">
                <h2>Terms & Conditions</h2>
                <ol>
                    <li><a href="<?php echo base_url(); ?>#hero">Home</a></li>
                    <li>Terms & Conditions</li>
                </ol>
            </div>

        </div>
    </section><!-- End Breadcrumbs Section -->

    <section class="inner-page">

        <div class="container">

<p class="p-text-center"><strong><span style="font-size:25px;line-height:200%;">TERMS AND CONDITIONS OF SERVICE</span></strong></p>
<p class="p-text-justify">Effective Date: April 1, 2021</p>
<p class="p-text-justify"><em>Website Covered: <a href="http://www.squill.in">www.squill.in</a></em></p>
<p class="p-text-justify"><em>App Covered: Squill App</em></p><br>
<p class="p-text-justify"><strong>THE AGREEMENT</strong>: The use of this Website/App and services on this Website/App provided by Satrango Private Limited (hereinafter referred to as &quot;Owner&quot;) are subject to the following Terms &amp; Conditions (hereinafter the &quot;Terms of Service&quot;), all parts and sub-parts of which are specifically incorporated by reference here together with the Privacy Policy. Following are the Terms of Service governing your use of www.squill.in(the &quot;Website&quot;) or Squill App (the &ldquo;App), all pages on the Website/App and any services provided by or on this Website/App (&quot;Services&quot;).</p>
<p class="p-text-justify">By accessing either directly or through a hyperlink or by installing App from respective Google Play Store or Apple I-Tunes Store, the Website/App, and/ or purchasing something from us, you engage in our &quot;Service&quot; and agree to be bound by the Terms of Service including those additional terms and conditions and policies referenced herein and/or available by hyperlink. These Terms of Service apply to all users of the site, including without limitation vendors, buyers, customers, merchants, browsers and/ or contributors of content. You acknowledge and agree that the Website/App may use your personal information in the manner described in our Privacy Policy which sets forth how information collected about you is collected, used and stored.</p>
<p class="p-text-justify"><strong>1) DEFINITIONS</strong></p>
<p class="p-text-justify">The parties referred to in these Terms of Service shall be defined as follows:</p>
<p class="p-text-subpara">a) <strong><em>Owner, Us, We</em></strong>: The Owner, as the creator, operator, and publisher of the Website/App, makes the Website/App, and certain Services on it, available to users. &nbsp;Satrango Private Limited, Owner, Us, We, Our, Ours and other first-person pronouns will refer to the Owner, as well as all employees and affiliates of the Owner.</p>
<p class="p-text-subpara">b) <strong><em>You, the User, the Client</em></strong>: You, as the user of the Website/App, will be referred to throughout these Terms of Service with second-person pronouns such as You, Your, Yours, or as User or Client. For the purpose of these Terms of Service, the term &quot;User&quot; or &quot;you&quot; shall mean any natural or legal person who person is accessing the Website/App. The term &apos;&quot;Your&quot; shall be construed accordingly.</p>
<p class="p-text-subpara">c) <strong><em>Parties</em></strong>: Collectively, the parties to these Terms of Service (the Owner and You) will be referred to as Parties.</p>
<p class="p-text-justify"><strong>2) ASSENT &amp; ACCEPTANCE</strong></p>
<p class="p-text-subpara">By using the Website/App, You warrant that You have read and reviewed these Terms of Service and that You agree to be bound by it. If You do not agree to be bound by these Terms of Service, please leave the Website/App immediately. The Owner only agrees to provide use of this Website/App and Services to You if You assent to these Terms of Service. Further, based on the Services obtained by a User, additional terms and conditions in respect of the specific Services may apply, which shall be deemed an agreement between the Users and the Owner.</p>
<p class="p-text-justify"><strong>3) AGE RESTRICTION</strong></p>
<p class="p-text-subpara">You must be at least 13 (thirteen) years of age to use this Website/App or any Services contained herein. By using this Website/App, You represent and warrant that You are at least 13 years of age. The Owner assumes no responsibility or liability for any misrepresentation of Your age.</p>
<p class="p-text-justify"><strong>4) ABOUT THE SITE/APP&nbsp;</strong></p>
<p class="p-text-subpara">The Website/App is an online marketplace platform which connects service providers that provide the following: Single Move services, Multi Move Services and Blue Collar Services with potential customers. We reserve the right to refuse service or refuse to sell the subscriptions on the Website/App or cancel the bookings at our sole discretion to anyone for any reason at any time.</p>
<p class="p-text-subpara">The Website/App does not screen or censor the users who register on and access the Website/App. You assume all risks associated with dealing with other users with whom you come in contact through the Website/App. You agree to use the Website/App only for lawful purposes without infringing the rights or restricting the use of this Website/App by any third party.</p>
<p class="p-text-justify"><strong>5) LICENSE TO USE WEBSITE/APP</strong></p>
<p class="p-text-subpara">The Owner may provide You with certain information as a result of Your use of the Website/App or Services. Such information may include but is not limited to, documentation, data, or information developed by the Owner, and other materials which may assist in Your use of the Website/App or Services (&quot;Owner Materials&quot;). Subject to these Terms of Service, the Owner grants You a non-exclusive, limited, non-transferable and revocable license to use the Owner Materials solely in connection with Your use of the Website/App and Services. The Owner Materials may not be used for any other purpose and this license terminates upon Your cessation of use of the Website/App or Services or at the termination of these Terms of Service.</p>
<p class="p-text-subpara">You agree not to collect contact information of other Users from the Website/App or download or copy any information by means of unsolicited access so as to communicate directly with them or for any reason whatsoever.</p>
<p class="p-text-subpara">Any unauthorized use by you shall terminate the permission or license granted to you by the Website/App and You agree that you shall not bypass any measures used by the Owner to prevent or restrict access to the Website/App.</p>
<p class="p-text-justify"><strong>6) INTELLECTUAL PROPERTY</strong></p>
<p class="p-text-subpara">You agree that the Website/App and all Services provided by the Owner are the property of the Owner, including all copyrights, trademarks, trade secrets, patents and other intellectual property (&quot;Owner IP&quot;). You agree that the Owner owns all right, title and interest in and to the Owner IP and that You will not use the Owner IP for any unlawful or infringing purpose. You agree not to reproduce or distribute the Owner IP in any way, including electronically or via registration of any new trademarks, trade names, service marks or Uniform Resource Locators (URLs), without express written permission from the Owner.</p>
<p class="p-text-justify"><strong>7) USER OBLIGATIONS</strong></p>
<p class="p-text-subpara">As a user of the Website/App or Services, You may be asked to register with Us. When You do so, You will choose a user identifier, which may be Your email address or mobile number or another term, as well as a password. You may also provide personal information, including, but not limited to, Your name. You are responsible for ensuring the accuracy of this information. This identifying information will enable You to use the Website/App and Services. You must not share such identifying information with any third party and if You discover that Your identifying information has been compromised, You agree to notify Us immediately in writing. An email notification will suffice. You are responsible for maintaining the safety and security of Your identifying information as well as keeping Us apprised of any changes to Your identifying information. The billing information You provide us, including credit card, billing address and other payment information, is subject to the same confidentiality and accuracy requirements as the rest of Your identifying information. Providing false or inaccurate information, or using the Website/App or Services to further fraud or unlawful activity is grounds for immediate termination of these Terms of Service. The Owner reserves the right to refuse service, terminate accounts, or remove or edit content in its sole discretion.</p>
<p class="p-text-justify"><strong>8) PAYMENT &amp; FEES</strong></p>
<p class="p-text-subpara">Should You register for any of the paid Services on this Website/App or purchase any product or service on this Website/App, You agree to pay us the specific monetary amounts required for that product or those Services. These monetary amounts (&quot;Fees/ Service Charges&quot;) will be described to You during Your account registration and/or confirmation process. The final amount required for payment will be shown to You immediately prior to purchase.</p>
<p class="p-text-subpara">We reserve the right to refuse service or refuse to sell the products on the Website/App at our sole discretion to anyone for any reason at any time.</p>
<p class="p-text-justify"><strong>9) ACCEPTABLE USE</strong></p>
<p class="p-text-subpara">You agree not to use the Website/App or Services for any unlawful purpose or any purpose prohibited under this clause. You agree not to use the Website/App or Services in any way that could damage the Website/App, Services or general business of the Owner.</p>
<p class="p-text-subpara">a) You further agree not to use the Website/App or Services:</p>
<p class="p-text-list">I) To harass, abuse, or threaten others or otherwise violate any person&apos;s legal rights;</p>
<p class="p-text-list">II) To violate any intellectual property rights of the Owner or any third party;</p>
<p class="p-text-list">III) To upload or otherwise disseminate any computer viruses or other software that may damage the property of another;</p>
<p class="p-text-list">IV) To perpetrate any fraud;</p>
<p class="p-text-list">V) To engage in or create any unlawful gambling, sweepstakes, or pyramid scheme;</p>
<p class="p-text-list">VI) To publish or distribute any obscene or defamatory material;</p>
<p class="p-text-list">VII) To publish or distribute any material that incites violence, hate or discrimination towards any group;</p>
<p class="p-text-list">VIII) To unlawfully gather information about others.</p>
<p class="p-text-subpara">You are prohibited from using the site or its content:</p>
<p class="p-text-subpara">(a) for any unlawful purpose;</p>
<p class="p-text-subpara">(b) to solicit others to perform or participate in any unlawful acts;</p>
<p class="p-text-subpara">(c) to infringe on any third party&apos;s intellectual property or proprietary rights, or rights of publicity or privacy, whether knowingly or unknowingly;</p>
<p class="p-text-subpara">(d) to violate any local, federal or international law, statute, ordinance or regulation;</p>
<p class="p-text-subpara">(e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability;</p>
<p class="p-text-subpara">(f) to submit false or misleading information or any content which is defamatory, libelous, threatening, unlawful, harassing, indecent, abusive, obscene, or lewd and lascivious or pornographic, or exploits minors in any way or assists in human trafficking or content that would violate rights of publicity and/or privacy or that would violate any law;</p>
<p class="p-text-subpara">(g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related Website/App, other Website/Apps, or the Internet; (h) to collect or track the personal information of others;</p>
<p class="p-text-subpara">(i) to damage, disable, overburden, or impair the Website/App or any other party&apos;s use of the Website/App;</p>
<p class="p-text-subpara">(j) to spam, phish, pharm, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or</p>
<p class="p-text-subpara">(k) to interfere with or circumvent the security features of the Service or any related Website/App, other Website/Apps, or the Internet;</p>
<p class="p-text-subpara">(l) to personally threaten or has the effect of personally threatening other Users. We reserve the right to terminate your use of the Service or any related Website/App for violating any of the prohibited uses. The Company has the full authority to review all content posted by Users on the Website/App. You acknowledge that the Website/App is not responsible or liable and does not control the content of any information that may be posted to the Website/App by You or other User of the Website/App and you are solely responsible for the same. You agree that You shall not upload, post, or transmit any content that you do not have a right to make available (such as, the intellectual property of another party).</p>
<p class="p-text-subpara">You agree to comply with all applicable laws, statutes and regulations concerning your use of the Website/App and further agree that you will not transmit any information, data, text, files, links, software, chats, communication or other materials that are abusive, invasive of another&apos;s privacy, harassing, defamatory, vulgar, obscene, unlawful, false, misleading, harmful, threatening, hateful or racially or otherwise objectionable, including without limitation material of any kind or nature that encourages conduct that could constitute a criminal offence, give rise to civil liability or otherwise violate any applicable local, state, provincial, national, or international law or regulation, or encourage the use of controlled substances.</p>
<p class="p-text-subpara">We may, but have no obligation to, monitor, edit or remove content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party&apos;s intellectual property or these Terms of Service.</p>
<p class="p-text-subpara">You may not use our products for any illegal or unauthorized purpose nor may you, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws).</p>
<p class="p-text-justify"><strong>10) COMMUNICATION</strong></p>
<p class="p-text-subpara">You understand that each time uses the Website/App in any manner, you agree to these Terms. By agreeing to these Terms, you acknowledge that you are interested in availing and purchasing the Services that you have selected and consent to receive communications via phone or electronic records from the Website/App including e-mail messages telling you about products and services offered by the Website/App (or its affiliates and partners) and understanding your requirements. Communication can also be by posting any notices on the Website/App. You agree that the communications sent to You by the Website/App shall not be construed as spam or bulk under any law prevailing in any country where such communication is received.</p>
<p class="p-text-justify"><strong>11) PRIVACY INFORMATION</strong></p>
<p class="p-text-subpara">Through Your Use of the Website/App and Services, You may provide Us with certain information. By using the Website/App or the Services, You authorize the Owner to use Your information in India and any other country where We may operate.</p>
<p class="p-text-subpara">a) <em><u>Information We May Collect or Receive</u>:</em> When You register for an account, You provide Us with a valid email address and may provide Us with additional information, such as Your name or billing information. Depending on how You use Our Website/App or Services, We may also receive information from external applications You use to access Our Website/App, or We may receive information through various web technologies, such as cookies, log files, clear gifs, web beacons or others.</p>
<p class="p-text-subpara">b) <em><u>How We Use Information:</u></em> We use the information gathered from You to ensure Your continued good experience on Our Website/App, including through email communication. We may also track certain of the passive information received to improve Our marketing and analytics, and for this, We may work with third-party providers.</p>
<p class="p-text-subpara">c) <em><u>How You Can Protect Your Information</u></em>: If You would like to disable Our access to any passive information We receive from the use of various technologies, You may choose to disable cookies in Your web browser. Please be aware that the Owner will still receive information about You that You have provided, such as Your email address.</p>
<p class="p-text-justify"><strong>12) ASSUMPTION OF RISK</strong></p>
<p class="p-text-subpara">The Website/App and Services are provided for communication purposes only. You acknowledge and agree that any information posted on Our Website/App is not intended to be legal advice, medical advice, or financial advice, and no fiduciary relationship has been created between You and the Owner. You further agree that Your purchase of any of the products on the Website/App is at Your own risk. The Owner does not assume responsibility or liability for any advice or other information given on the Website/App.</p>
<p class="p-text-justify"><strong>13) SALE OF GOODS/SERVICES</strong></p>
<p class="p-text-subpara">The Owner may sell goods or services or allow third parties to sell goods or services on the Website/App. The Owner undertakes to be as accurate as possible with all information regarding the goods and services, including product descriptions and images. However, the Owner does not guarantee the accuracy or reliability of any product information and You acknowledge and agree that You purchase such products at Your own risk. For goods or services sold by others, the Owner assumes no liability for any product and cannot make any warranties about the merchantability, fitness, quality, safety or legality of these products. For any claim You may have against the manufacturer or seller of the product, You agree to pursue that claim directly with the manufacturer or seller and not with the Owner. You hereby release the Owner from any claims related to goods or services manufactured or sold by third parties, including any and all warranty or product liability claims.</p>
<p class="p-text-subpara">We may, in our sole discretion, limit or cancel quantities purchased per person, per household or per order. Any orders including orders by or under the same customer account, the same credit card, and/or orders that use the same billing and/or shipping address may be subject to the above. We may restrict the sales of products or Services to any person, geographic region or jurisdiction at our sole discretion as we may decide on a case-by-case basis.</p>
<p class="p-text-justify">We further reserve an absolute right to refuse any order placed by any person and to limit or prohibit orders that, in our sole judgment, appear to be placed by dealers, resellers or distributors. If we cancel your order, we will contact the e-mail and/or billing address/phone number provided at the time the order was made.</p>
<p class="p-text-justify">We take care to accurately display the colours and images of our products but, we cannot guarantee that your computer or phone screen&apos;s display of any colour will be accurate. We also do not provide any warranties that the quality of any products, services, information, or other material purchased or obtained by you will meet your expectations and standards, or that any errors in the Service will be corrected. Prices and descriptions of products are subject to change at any time without notice, at our sole discretion. We may remove or discontinue any products from our site without prior notice. Any offer for any product or service made on this site is void where prohibited.</p>
<p class="p-text-justify">We may provide you with access to third-party tools over which we neither monitor nor have any control nor input. You acknowledge and agree that we provide access to such tools &quot;as is&quot; and &quot;as available&quot; without any warranties, representations or conditions of any kind and without any endorsement. We shall have no liability whatsoever arising from or relating to your use of optional third-party tools. Any use by you of optional tools offered through the site is entirely at your own risk and discretion and you should ensure that you are familiar with and approve of the terms on which tools are provided by the relevant third-party provider(s). If You are unhappy with a service being sold on Our Website/App, You may request a refund.</p>
<p class="p-text-justify">We will make reimbursements for returns without undue delay, and not later than:</p>
<p class="p-text-list">(i) 07 working days after the day we received any request for cancellation of booking from you with in the stipulated time; or</p>
<p class="p-text-list">(ii) you provide evidence that you have not utilized the services; or</p>
<p class="p-text-list">(iii) if services provided by the service provider are not according to the description you have mentioned before booking or has not solved the purpose of hiring the service provider, in such case support ticket for refund should be raised before 48 hours after the completion of the booking to initiate refunds if any.</p>
<p class="p-text-list">(iv) No Refund will be provided other than the above mentioned clauses.</p>
<p class="p-text-justify">We will make the reimbursement using the same means of payment as you used for the initial transaction unless you have expressly agreed otherwise; in any event, you will not incur any fees as a result of the reimbursement.</p>
<p class="p-text-justify"><strong>14) REVERSE ENGINEERING &amp; SECURITY</strong></p>
<p class="p-text-subpara">You agree not to undertake any of the following actions:</p>
<p class="p-text-subpara">a) Reverse engineer, or attempt to reverse engineer or disassemble any code or software from or on the Website/App or Services;</p>
<p class="p-text-subpara">b) Violate the security of the Website/App or Services through any unauthorized access, circumvention of encryption or other security tools, data mining or interference to any host, user or network.</p>
<p class="p-text-justify"><strong>15) DATA LOSS</strong></p>
<p class="p-text-subpara">The Owner does not accept responsibility for the security of Your account or content. You agree that Your use of the Website/App or Services is at Your own risk. Our platform could be vulnerable to hacking, virus attacks and your personal data may be at risk. We take all the necessary and reasonable caution to protect our Service and data.</p>
<p class="p-text-justify"><strong>16) INDEMNIFICATION</strong></p>
<p class="p-text-subpara">You agree to defend and indemnify the Owner and any of its affiliates (if applicable) and hold Us harmless against any and all legal claims and demands, including reasonable attorney&apos;s fees, which may arise from or relate to Your use or misuse of the Website/App or Services, Your breach of these Terms of Service, or Your conduct or actions. You agree that the Owner shall be able to select its own legal counsel and may participate in its own defence if the Owner wishes.</p>
<p class="p-text-justify"><strong>17) SPAM POLICY</strong></p>
<p class="p-text-subpara">You are strictly prohibited from using the Website/App or any of the Owner&apos;s Services for illegal spam activities, including gathering email addresses and personal information from others or sending any mass commercial emails.</p>
<p class="p-text-justify"><strong>18) THIRD-PARTY LINKS &amp; CONTENT</strong></p>
<p class="p-text-subpara">The Owner may occasionally post links to third-party Website/Apps or other services. You agree that the Owner is not responsible or liable for any loss or damage caused as a result of Your use of any third party services linked to from Our Website/App.</p>
<p class="p-text-justify"><strong>19) MODIFICATION &amp; VARIATION</strong></p>
<p class="p-text-subpara">The Owner may, from time to time and at any time without notice to You, modify these Terms of Service. You agree that the Owner has the right to modify these Terms of Service or revise anything contained herein. You further agree that all modifications to these Terms of Service are in full force and effect immediately upon posting on the Website/App and that modifications or variations will replace any prior version of these Terms of Service unless prior versions are specifically referred to or incorporated into the latest modification or variation of these Terms of Service.</p>
<p class="p-text-subpara">a) To the extent any part or sub-part of these Terms of Service is held ineffective or invalid by any court of law, You agree that the prior, effective version of these Terms of Service shall be considered enforceable and valid to the fullest extent.</p>
<p class="p-text-subpara">b) You agree to routinely monitor these Terms of Service and refer to the Effective Date posted at the top of these Terms of Service to note modifications or variations. You further agree to clear Your cache when doing so to avoid accessing a prior version of these Terms of Service. You agree that Your continued use of the Website/App after any modifications to these Terms of Service is a manifestation of Your continued assent to these Terms of Service.</p>
<p class="p-text-subpara">c) In the event that You fail to monitor any modifications to or variations of these Terms of Service, You agree that such failure shall be considered an affirmative waiver of Your right to review the modified Agreement.</p>
<p class="p-text-justify"><strong>20) ENTIRE AGREEMENT</strong></p>
<p class="p-text-subpara">This Agreement constitutes the entire understanding between the Parties with respect to any and all use of this Website/App. This Agreement supersedes and replaces all prior or contemporaneous agreements or understandings, written or oral, regarding the use of this Website/App.</p>
<p class="p-text-justify"><strong>21) SERVICE INTERRUPTIONS</strong></p>
<p class="p-text-subpara">The Owner may need to interrupt Your access to the Website/App to perform maintenance or emergency services on a scheduled or unscheduled basis. You agree that Your access to the Website/App may be affected by unanticipated or unscheduled downtime, for any reason, but that the Owner shall have no liability for any damage or loss caused as a result of such downtime.</p>
<p class="p-text-justify"><strong>22) TERM, TERMINATION &amp; SUSPENSION</strong></p>
<p class="p-text-subpara">The Owner may terminate these Terms of Service with You at any time for any reason, with or without cause. The Owner specifically reserves the right to terminate these Terms of Service if You violate any of the terms outlined herein, including, but not limited to, violating the intellectual property rights of the Owner or a third party, failing to comply with applicable laws or other legal obligations, and/or publishing or distributing illegal material. If You have registered for an account with Us, You may also terminate these Terms of Service at any time by contacting Us and requesting termination. Please keep in mind that any outstanding fees will still be due even after termination of Your account. At the termination of these Terms of Service, any provisions that would be expected to survive termination by their nature shall remain in full force and effect.</p>
<p class="p-text-justify"><strong>23) NO WARRANTIES</strong></p>
<p class="p-text-subpara">You agree that Your use of the Website/App and Services is at Your sole and exclusive risk and that any Services provided by Us are on an &quot;As Is&quot; basis. The Owner hereby expressly disclaims any and all express or implied warranties of any kind, including, but not limited to the implied warranty of fitness for a particular purpose and the implied warranty of merchantability. The Owner makes no warranties that the Website/App or Services will meet Your needs or that the Website/App or Services will be uninterrupted, error-free, or secure. The Owner also makes no warranties as to the reliability or accuracy of any information on the Website/App or obtained through the Services. You agree that any damage that may occur to You, through Your computer system, or as a result of the loss of Your data from Your use of the Website/App or Services is Your sole responsibility and that the Owner is not liable for any such damage or loss.</p>
<p class="p-text-subpara">All information, software, products, services and related graphics are provided on this site is &quot;as is&quot; and &quot;as available&quot; basis with without warranty of any kind, either expressed or implied. The Website/App disclaims all warranties, expressed or implied including, without limitation, all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement or arising from a course of dealing, usage, or trade practice. The company makes no representation about the suitability of the information, software, products, and services contained on this Website/App for any purpose, and the inclusion or offering of any products or services on this Website/App does not constitute any endorsement or recommendation of such products or services.</p>
<p class="p-text-subpara">The Website/App makes no warranty that the use of the Website/App will be uninterrupted, timely, secure, without defect or error-free. You expressly agree that use of the site is at your own risk. The Website/App shall not be responsible for any content found on the Website/App.</p>
<p class="p-text-subpara">Your use of any information or materials on this site or otherwise obtained through use of this Website/App is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products, services or information available through this Website/App meet your specific requirements.</p>
<p class="p-text-subpara">The Website/App assumes no responsibility for the accuracy, currency, completeness or usefulness of information, views, opinions or advice in any material contained on the Website/App. Any information of third parties or advertisers is made available without doing any changes and so the Website/App cannot guarantee accuracy and is not liable to any inconsistencies arising thereof. All postings, messages, advertisements, photos, sounds, images, text, files, video or other materials posted on, transmitted through, or linked from the Website/App, are solely the responsibility of the person from whom such Content originated and the Website/App does not control and is not responsible for Content available on the Website/App.</p>
<p class="p-text-subpara">There may be instances when incorrect information is published inadvertently on our Website/App or in the Service such as typographical errors, inaccuracies or omissions that may relate to product descriptions, pricing, promotions, offers, product shipping charges, transit times and availability. Any errors, inaccuracies or omissions, may be corrected at our discretion at any time and we may change or update information or cancel orders if any information in the Service or on any related Website/App is inaccurate at any time without prior notice (including after you have submitted your order).</p>
<p class="p-text-subpara">We undertake no obligation to update, amend or clarify information in the Service or on any related Website/App, including without limitation, pricing information, except as required by law. No specified update or refresh date applied in the Service or on any related Website/App should be taken to indicate that all information in the Service or on any related Website/App has been modified or updated.</p>
<p class="p-text-subpara">The Website/App shall not be responsible for any interaction between you and the other users of the Website/App. Under no circumstances will the Website/App be liable for any goods, services, resources or content available through such third party dealings or communications, or for any harm related thereto. The Website/App is under no obligation to become involved in any disputes between you and other users of the Website/App or between you and any other third parties. You agree to release the Website/App from any and all claims, demands, and damages arising out of or in connection with such dispute.</p>
<p class="p-text-subpara">You agree and understand that while the Website/App has made reasonable efforts to safeguard the Website/App, it cannot and does not ensure or make any representations that the Website/App or any of the information provided by You cannot be hacked by any unauthorised third parties. You specifically agree that the Website/App shall not be responsible for unauthorized access to or alteration of Your transmissions or data, any material or data sent or received or not sent or received, or any transactions entered into through the Website/App.</p>
<p class="p-text-subpara">You hereby agree and confirm that the Website/App shall not be held liable or responsible in any manner whatsoever for such hacking or any loss or damages suffered by you due to unauthorized access of the Website/App by third parties or for any such use of the information provided by You or any spam messages or information that You may receive from any such unauthorised third party (including those which are although sent representing the name of the Website/App but have not been authorized by the Website/App) which is in violation or contravention of this Terms of Service or the Privacy Policy.</p>
<p class="p-text-subpara">You specifically agree that the Website/App is not responsible or liable for any threatening, defamatory, obscene, offensive or illegal content or conduct of any other party or any infringement of another&apos;s rights, including intellectual property rights. You specifically agree that the Website/App is not responsible for any content sent using and/or included in the Website/App by any third party.</p>
<p class="p-text-subpara">The Website/App has no liability and will make no refund in the event of any delay, cancellation, strike, force majeure or other causes beyond their direct control, and they have no responsibility for any additional expense omissions delays or acts of any government or authority.</p>
<p class="p-text-subpara">You will be solely responsible for any damages to your computer system or loss of data that results from the download of any information and/or material. Some jurisdictions do not allow the exclusion of certain warranties, so some of the above exclusions may not apply to you.</p>
<p class="p-text-subpara">In no event shall the Website/App be liable for any direct, indirect, punitive, incidental, special, consequential damages or any damages whatsoever including, without limitation, damages for loss of use, data or profits, arising out of or in any way connected with the use or performance of the site, with the delay or inability to use the site or related services, the provision of or failure to provide Services, or to deliver the products or for any information, software, products, services and related graphics obtained through the site, or any interaction between you and other participants of the Website/App or otherwise arising out of the use of the Website/App, damages resulting from use of or reliance on the information present, whether based on contract, tort, negligence, strict liability or otherwise, even if the Website/App or any of its affiliates/suppliers has been advised of the possibility of damages. If despite the limitation above, the Company is found liable for any loss or damage which arises out of or in any way connected with the use of the Website/App and/ or provision of Services, then the liability of the Company will in no event exceed, 50% (Fifty percent) of the amount you paid to the Company in connection with such transaction(s) on this Website/App.</p>
<p class="p-text-subpara">You accept all responsibility for and hereby agree to indemnify and hold harmless the company from and against, any actions taken by you or by any person authorized to use your account, including without limitation, disclosure of passwords to third parties. By using the Website/App, you agree to defend, indemnify and hold harmless the indemnified parties from any and all liability regarding your use of the site or participation in any site&apos;s activities. If you are dissatisfied with the Website/App, or the Services or any portion thereof, or do not agree with these terms, your only recourse and exclusive remedy shall be to stop using the site.</p>
<p class="p-text-justify"><strong>24) LIMITATION ON LIABILITY</strong></p>
<p class="p-text-subpara">The Owner is not liable for any damages that may occur to You as a result of Your use of the Website/App or Services, to the fullest extent permitted by law. Further you agree that we shall, in no event, be liable for any consequential, incidental, indirect, special, punitive, or other loss or damage whatsoever or for loss of business profits, business interruption, computer failure, loss of business information, or other loss arising out of or caused by your use of or inability to use the service. Even if we have been advised of the possibility of such damage. In no event shall our entire liability to you in respect of any service, whether direct or indirect, exceed the fees paid by you towards such service. The maximum liability of the Owner arising from or relating to these Terms of Service will be Rs. 1,000/- (Rupees One Thousand Only) in any case or as decided by the judiciary authorities&rsquo; case to case.</p>
<p class="p-text-justify"><strong>25) YOUR CONTENT</strong></p>
<p class="p-text-subpara">The Services may contain information, text, links, graphics, photos, videos, or other materials (&ldquo;Content&rdquo;) including Content created with or submitted to the Services by you or through your account (&ldquo;Your Content&rdquo;). We take no responsibility for and we do not expressly or implicitly endorse any or your content.</p>
<p class="p-text-subpara">By submitting your content to the Services, you represent and warrant that you have all rights, power, and authority necessary to grant the rights to your content contained within these terms. Because you alone are responsible for your content. You may expose yourself to liability if you post or share content without all necessary rights.</p>
<p class="p-text-subpara">You retain the ownership rights you have in your content, but you grant us the following license to use that content:</p>
<p class="p-text-subpara">When your content is created with or submitted to the Services, you grant us a worldwide, royalty-free, perpetual, irrevocable, non-exclusive, transferable, and sublicensable license to copy, modify, adapt, prepare derivative works from, distribute, perform, and display your content and any name, username, voice or likeness provided in connection with your content in all media formats and channels known or later developed. This license includes the right to us to make your content available for syndication, broadcast, distribution, or publication by other companies, organizations, or individuals who partner with Satrango. You also agree that we may remove metadata associated with your content, and you irrevocably waive any claims and assertions of moral rights or attribution with respect to your content.</p>
<p class="p-text-subpara">Any ideas, suggestions and feedback about us or our services that you provide to us are entirely voluntary, and you agree that we may use such ideas, suggestions, and feedback without compensation or obligation to you.</p>
<p class="p-text-subpara">Although we have no obligation to screen, edit, or monitor your content, we may, in our sole discretion, delete or remove your content at any time and for any reason, including for a violation of these terms, a violation of our other policies, or if you otherwise create liability for us</p>
<p class="p-text-justify"><strong>25) GENERAL PROVISIONS</strong></p>
<p class="p-text-subpara">a) <em><u>LANGUAGE:</u></em> All communications made or notices given pursuant to these Terms of Service shall be in the English language.</p>
<p class="p-text-subpara">b) <em><u>JURISDICTION, VENUE &amp; GOVERNING LAW:</u></em> Through Your use of the Website/App or Services, You agree that the laws of India shall govern any matter or dispute relating to or arising out of these Terms of Service, as well as any dispute of any kind that may arise between You and the Owner, with the exception of its conflict of law provisions. In case any litigation specifically permitted under these Terms of Service is initiated, the Parties agree to submit to the exclusive jurisdiction of the courts at Vijayawada, Andhra Pradesh, India. The Parties agree that this choice of law, venue, and jurisdiction provision is not permissive, but rather mandatory in nature. You hereby waive the right to any objection of venue, including assertion of the doctrine of forum non-convenience or similar doctrine.</p>
<p class="p-text-subpara">c) <em><u>SEVERABILITY:</u></em> If any part or sub-part of these Terms of Service is held invalid or unenforceable by a court of law or competent arbitrator, the remaining parts and sub-parts will be enforced to the maximum extent possible. In such condition, the remainder of these Terms of Service shall continue in full force.</p>
<p class="p-text-subpara">e) <em><u>NO WAIVER:</u></em> In the event that We fail to enforce any provision of these Terms of Service, this shall not constitute a &nbsp;waiver such right or provision. If any provision of this agreement is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties&rsquo; intentions as reflected in the provision, and other provisions do this agreement remain in full force and effect. Waiver of any part or sub-part of these Terms of Service will not constitute a waiver of any other part or sub-part.</p>
<p class="p-text-subpara">f) <em><u>HEADINGS FOR CONVENIENCE ONLY:</u></em> Headings of parts and sub-parts under these Terms of Service are for convenience and organization, only. Headings shall not affect the meaning of any provisions of these Terms of Service.</p>
<p class="p-text-subpara">g) <em><u>NO AGENCY, PARTNERSHIP OR JOINT VENTURE:</u></em> No agency, partnership, or joint venture has been created between the Parties as a result of these Terms of Service. No Party has any authority to bind the other to third parties.</p>
<p class="p-text-subpara">h) <em><u>STATURE OF LIMITATION</u></em>: You agree that regardless of any stature or law to the contrary, any claim or cause of action arising out of or related to use of the Website/App or products or this agreement must be filed within Three (3) months after such claim or cause of action arose or be forever barred.</p>
<p class="p-text-subpara">i) <em><u>WAIVER OF CLASS ACTION RIGHTS</u></em>: By Entering into this agreement, you hereby irrevocably waive any right you may have to join claims with those of other in the form of a class action or similar procedural device. Any claims arising out of, relating to, or connection with this agreement must be asserted individually.</p>
<p class="p-text-subpara">k) <em><u>TERMINATION</u></em> : Satrango Private Limited reserves the right to terminate your access to the Website/App if it reasonably believes, in its sole discretion, that you have breached any of the terms and conditions of this agreement. Following termination, you will not be permitted to use the Website/App and Satrango Private Limited may, in its sole discretion and without advance notice to you, cancel any outstanding orders for products/ Services. If your access to the Website/App is terminated, Satrango Private Limited reserves the right to exercise whatever means it deems necessary to prevent unauthorized access of the Website/App. This agreement will survive indefinitely unless and until Satrango Private Limited chooses, in its sole discretion and without advance to you, to terminate it.</p>
<p class="p-text-subpara">l) <em><u>DOMESTIC USE:</u></em> Satrango Private Limited makes no representation that the Website/App or products/ services are appropriate or available for use in locations outside India. Users who access the Website/App from outside India do so at their own risk and initiative and must bear all responsibility for compliance with any applicable local laws.</p>
<p class="p-text-subpara">m) <em><u>ASSIGNMENT:</u></em> You may not assign your rights and obligations under this agreement to anyone. Satrango Private Limited may assign its rights and obligations under this agreement in its sole discretion and without advance notice to you.</p>
<p class="p-text-subpara">n) <em><u>SALES, PROMOTIONAL OFFERS, COUPONS AND PRICING</u></em>: Sales, Promotions and other special discounted pricing offers are temporary and, upon the renewal of your subscription, any such discounted pricing offers may expire. We reserve the right to discontinue or modify any coupons, credits, sales and special promotional offers in our sole discretion.</p>
<p class="p-text-subpara">n) <em><u>TAXES AND WITHHOLDING</u></em>: You are responsible for all applicable sales, service, value added, goods and services, withholding, tariffs and similar taxes (Collectively &ldquo;Taxes&rdquo;) imposed by any Government entity or collecting agency based on the Services, except those Taxes based on our net income, or Taxes for which you have provided an exemption certificate. Additionally, if you do not satisfy your Tax obligations, you agree that you will be required to reimburse us for any Taxes paid on your behalf, and we may take steps to collect Taxes we have paid on your behalf. In all cases, you will pay the amounts due under this Agreement to us in full without any right of set-off or deduction.</p>
<p class="p-text-subpara">o) <em><u>ELECTRONIC COMMUNICATIONS PERMITTED:</u></em> Electronic communications are permitted to both Parties under these Terms of Service, including e-mail or fax. For any questions or concerns, please email Us at the following address: <a href="mailto:admin@satrango.com">admin@satrango.com</a>.</p>
<p class="p-text-subpara">BY USING THIS WEBSITE/APP OR ORDERING SERVICES FROM THIS WEBSITE/APP YOU AGREE TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT.</p>
        </div>
    </section>

</main>
<!-- End #main -->

<?php $this->endsection() ?>


<?php $this->section('script') ?>


<?php $this->endsection() ?>